spring:
  application:
    name: ava-mall-search
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      poll-interval: 5s
      quiet-period: 3s

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
