spring:
  application:
    name: ava-mall-front-api
  profiles:
    active: dev

# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.lucien.**.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  config-location: classpath:mybatis/mybatisConfig.xml

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
